config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "home", to: "home#index"

  resources :books, only: [:index, :show, :new, :edit, :create, :update] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, presence: true
    validates :pages_count, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  private

    def book_params
      params.require(:book).permit(:title, :author, :description, :pages_count, :published_at)
    end

    def find_book
      @book = Book.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true, data: { turbo: false } do |form| %>

  <% if @book.errors.any? %>
    <h2>
      <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :pages_count %><br>
    <%= form.number_field :pages_count %>
  </p>

  <p>
    <%= form.label :published_at %><br>
    <%= form.date_field :published_at %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit the book</h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1>All the books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<h1>Create a new book</h1>

<%= render "form" %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong><%= @book.author %> - <%= @book.published_at %> - <%= @book.pages_count %> pages</strong></p>
<p><%= @book.description %></p>

app/views/home/index.html.erb
<h1>Books Open Database </h1>
<p> Not much for now, but hey ! Hello world !</p>
<%= link_to "All the books", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksOdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>